In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("pima-indians-diabetes.csv",names=['preg','plas','pres','skin','test','mass','pedi','age','class'])
data

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

## Convert 0 to NAN for Imputer

In [3]:
data.replace({'test':0,'skin':0},np.nan,inplace=True)
data

preg  plas  pres  skin   test  mass   pedi  age  class
0       6   148    72  35.0    NaN  33.6  0.627   50      1
1       1    85    66  29.0    NaN  26.6  0.351   31      0
2       8   183    64   NaN    NaN  23.3  0.672   32      1
3       1    89    66  23.0   94.0  28.1  0.167   21      0
4       0   137    40  35.0  168.0  43.1  2.288   33      1
..    ...   ...   ...   ...    ...   ...    ...  ...    ...
763    10   101    76  48.0  180.0  32.9  0.171   63      0
764     2   122    70  27.0    NaN  36.8  0.340   27      0
765     5   121    72  23.0  112.0  26.2  0.245   30      0
766     1   126    60   NaN    NaN  30.1  0.349   47      1
767     1    93    70  31.0    NaN  30.4  0.315   23      0

[768 rows x 9 columns]

## KNN Imputer

In [4]:
from sklearn.impute import KNNImputer

In [5]:
imputer=KNNImputer(n_neighbors=3)
data=imputer.fit_transform(data)
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

## Min Max Scaler

This estimator scales and translates each feature individually such that it is in the given range on the training set, e.g. between zero and one.

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
scaler=MinMaxScaler()
data=scaler.fit_transform(data)
data

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.23441503, 0.48333333,
        1.        ],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.11656704, 0.16666667,
        0.        ],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.25362938, 0.18333333,
        1.        ],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.07130658, 0.15      ,
        0.        ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.11571307, 0.43333333,
        1.        ],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.10119556, 0.03333333,
        0.        ]])

## L2Norm

In [8]:
from sklearn.preprocessing import Normalizer

In [9]:
norm=Normalizer()
data=norm.fit_transform(data)
data

array([[0.21576149, 0.45465319, 0.36078151, ..., 0.14330359, 0.29547338,
        0.61132423],
       [0.06846077, 0.49711461, 0.62961459, ..., 0.13566457, 0.19397217,
        0.        ],
       [0.28796015, 0.56271609, 0.32100475, ..., 0.1551997 , 0.11218447,
        0.61191531],
       ...,
       [0.28998908, 0.59950507, 0.58187974, ..., 0.07030564, 0.14789443,
        0.        ],
       [0.0400252 , 0.43082401, 0.33463692, ..., 0.07873446, 0.29485231,
        0.6804284 ],
       [0.06416727, 0.50979121, 0.62589385, ..., 0.11038852, 0.03636145,
        0.        ]])

## Binarizer
Binarize data (set feature values to 0 or 1) according to a threshold.

Values greater than the threshold map to 1, while values less than or equal to the threshold map to 0. With the default threshold of 0, only positive values map to 1.

In [10]:
from sklearn.preprocessing import Binarizer


In [11]:
binarizer=Binarizer(threshold=0.0)
data_b=binarizer.fit_transform(data)
data_b

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])